# Generated by Django 3.1 on 2020-12-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=500)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('cv', models.FileField(blank=True, upload_to='photoident')),
                ('experience', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=50)),
                ('photopi', models.FileField(blank=True, upload_to='photoident')),
                ('phOto', models.ImageField(blank=True, upload_to='photoperso')),
            ],
        ),
        migrations.CreateModel(
            name='Repetiteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=500)),
                ('ville', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('niveau', models.CharField(max_length=200)),
                ('telephone', models.IntegerField()),
                ('photopi', models.FileField(upload_to='photoident')),
                ('phOto', models.ImageField(upload_to='photoperso')),
            ],
        ),
    ]
