# Generated by Django 3.1 on 2021-01-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='note')),
                ('nom', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='cv',
            field=models.FileField(blank=True, upload_to='photoform'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='phOto',
            field=models.ImageField(blank=True, upload_to='photoform'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='photopi',
            field=models.FileField(blank=True, upload_to='photoform'),
        ),
        migrations.AlterField(
            model_name='repetiteur',
            name='phOto',
            field=models.ImageField(upload_to='stokRepetiteur'),
        ),
        migrations.AlterField(
            model_name='repetiteur',
            name='photopi',
            field=models.FileField(upload_to='stokRepetiteur'),
        ),
    ]
