# Generated by Django 3.1 on 2021-02-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defile',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
