# Generated by Django 3.1 on 2021-02-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_defile_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetiteur',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
