# Generated by Django 3.1 on 2021-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_repetiteur_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetiteur',
            name='slug',
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='cv',
            field=models.FileField(blank=True, upload_to='stokRepetiteur'),
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='niveauEnsei',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repetiteur',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
