# Generated by Django 3.1 on 2021-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210215_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='niveauEnsei',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='prix',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
