# Generated by Django 3.1 on 2021-02-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210222_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='niveauEnsei',
            field=models.CharField(max_length=1000),
        ),
    ]
