# Generated by Django 3.1 on 2021-01-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210116_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetiteur',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='stokRepetiteur'),
        ),
    ]
