# Generated by Django 3.1 on 2021-02-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210223_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='defile',
            name='telerphone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
