# Generated by Django 3.1 on 2021-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210119_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='cv',
            field=models.FileField(blank=True, upload_to='photoform'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='phOto',
            field=models.ImageField(blank=True, upload_to='photoform'),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='photopi',
            field=models.FileField(blank=True, upload_to='photoform'),
        ),
    ]
